import { Inter } from "next/font/google";
import "./globals.css";
import RouteNavbar from "./components/RouteNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ScriptParty",
  description: "Generated by create next app",
  icons: {
    icon: "/scriptparty.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} layout`}>
        <RouteNavbar />
        {children}
      </body>
    </html>
  );
}
